"""init tables

Revision ID: 6265c19e0292
Revises: 
Create Date: 2026-06-17 17:16:25.557601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6265c19e0292'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='企业名称'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='登录邮箱，唯一'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt加密后的密码'),
    sa.Column('api_key', sa.String(length=64), nullable=False, comment='服务端API对接密钥，注册时自动生成'),
    sa.Column('plan', sa.String(length=20), nullable=True, comment='套餐：free/pro，用于配额和限流'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用，禁用后所有接口不可访问'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='所属租户'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='服务器存储路径'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='处理状态：pending=等待处理, processing=解析中, ready=可用, failed=失败'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='切分后的片段数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='所属租户'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='终端用户标识'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False, comment='所属文档'),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='所属租户'),
    sa.Column('content', sa.String(), nullable=False, comment='切分后的原文内容'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='该片段的token数'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='在文档中的顺序，从0开始'),
    sa.Column('vector_id', sa.String(), nullable=True, comment='Qdrant中的向量ID，用于后续检索关联'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_tenant_id'), 'chunks', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False, comment='所属会话'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色：user=用户, assistant=AI, system=系统'),
    sa.Column('content', sa.String(), nullable=False, comment='消息内容'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='该消息的token数，用于上下文长度控制'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chunks_tenant_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
