"""add summary fields to sessions

Revision ID: d343909df1dd
Revises: f657c1b02b53
Create Date: 2026-07-01 16:30:59.873383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd343909df1dd'
down_revision: Union[str, None] = 'f657c1b02b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('summary', sa.String(), nullable=True, comment='对话历史摘要，用于长对话上下文管理'))
    op.add_column('sessions', sa.Column('summary_count', sa.Integer(), nullable=True, comment='摘要覆盖的消息条数，用于增量更新判断'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'summary_count')
    op.drop_column('sessions', 'summary')
    # ### end Alembic commands ###
