"""add file_hash to documents

Revision ID: f657c1b02b53
Revises: 6265c19e0292
Create Date: 2026-06-30 14:29:26.931147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f657c1b02b53'
down_revision: Union[str, None] = '6265c19e0292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True, comment='文件内容SHA256，用于去重'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
